import type { Metadata } from "next";
import "./globals.css";
import { GlobalErrorProvider } from "@/context/global.error.context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ height: "100vh", padding: 4, margin: 0 }}>
        <GlobalErrorProvider>{children}</GlobalErrorProvider>
      </body>
    </html>
  );
}
